# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea3933cfd340eae3f5d20f28c15b7ed2687f0fa53fb720cda5452b0898a5a2dba274d8ff73e87c3eda2b1a142ca04e9a0d082fad5345e9fc3b1d6f46a09479b8

test:
  secret_key_base: 3db820ec9d016f7fe807f3aab8123b1739c1e3a747a627f26ee1f34731420e141d65a46ee36e7f71eb516ab7fd6d3920a6cd5b00a9fca130b6916d757b04fc91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
